### ISSUE TITLE
Can't toggle HyperChat in archived streams

### ISSUE THREAD

**Issue by r2dev2** [LiveTL/chat#18]
![image](https://user-images.githubusercontent.com/50760816/128065142-2550f0ba-0e53-4a54-a5ec-13544c65fc10.png)

I can't toggle HyperChat in [archived streams](https://www.youtube.com/watch?v=Lovz9hosw7Q). I can still toggle it while the stream is live.

**Comment by ChrRubin** [comment]
Seems to be only affecting Firefox, I'll check it out later.

**Comment by ChrRubin** [comment]
Just a script load order issue, fixed in LiveTL/LiveTL@2f91bfb.

**Comment by ChrRubin** [comment]
The main issue was that the translator mode script getting TypeError'd since there's no `#input` for VODs (and also subs/members only's, which I saw some people having problems with). 

I'm guessing Firefox stops further scripts from being injected once one errors out. Nonetheless, both issues are fixed in the main LiveTL repo.
